# Getting Started with pandas

In [ ]:
import pandas as pd

In [ ]:
# two workhorse data structures: Series and Dataframe
from pandas import Series, DataFrame 

In [ ]:
import numpy as np
np.random.seed(12345)
import matplotlib.pyplot as plt
plt.rc('figure', figsize=(10, 6))
PREVIOUS_MAX_ROWS = pd.options.display.max_rows
pd.options.display.max_rows = 20
np.set_printoptions(precision=4, suppress=True)

## Introduction to pandas Data Structures

### Series

In [ ]:
obj = pd.Series([4, 7, -5, 3])
type(obj) # pandas.core.series.Series

obj

In [ ]:
obj.values # array([ 4,  7, -5,  3])
obj.index  # like range(4)

In [ ]:
# Pandas Series
obj2 = pd.Series([4, 7, -5, 3], index=['d', 'b', 'a', 'c'])
obj2.index # Index(['d', 'b', 'a', 'c'], dtype='object')
obj2

In [ ]:
# pd.Series
obj2['a'] # -5
obj2['d'] = 6
obj2[['c', 'a', 'd']]

In [ ]:
obj2[obj2 > 3]

In [ ]:
obj2 * 2

In [ ]:
np.exp(obj2)

In [ ]:
'b' in obj2

In [ ]:
'e' in obj2

In [ ]:
# Pandas series -- like dictionaries
sdata = {'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000} # This IS A DICTIONARY
obj3 = pd.Series(sdata) # make a Pandas series out of it
obj3

In [ ]:
# Pandas series = pd.Series
states = ['California', 'Ohio', 'Oregon', 'Texas'] 
print(obj3)
obj4 = pd.Series(sdata, index=states) # override default index ordering
obj4

In [ ]:
# Pandas: 'missing' = 'NA' --> use pd.isnull()
pd.isnull(obj4) # DETECT MISSING DATA

In [ ]:
pd.notnull(obj4) # pandas top-level function

In [ ]:
obj4.isnull() # ALSO series instance method

In [ ]:
obj3

In [ ]:
obj4

In [ ]:
obj3 + obj4 # AUTOMATICALLY ALIGNS BY INDEX LABEL

In [ ]:
obj4.name = 'population' # series name
obj4.index.name = 'state' # index name
obj4

In [ ]:
print(obj)
obj.index = ['Bob', 'Steve', 'Jeff', 'Ryan'] # changed in place (Boom!)
obj

### DataFrame - big kahuna

In [ ]:
# Pandas. DataFrame. Believe it.

data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
        'year': [2000, 2001, 2002, 2001, 2002, 2003],
        'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}
frame = pd.DataFrame(data)
# keys become columns, values become rows

In [ ]:
frame # beautiful

In [ ]:
frame.head() # first 5 rows

In [ ]:
data
# type(data) # dict

In [ ]:
pd.DataFrame(data, columns=['year', 'state', 'pop'])

In [ ]:
frame2 = pd.DataFrame(data, columns=['year', 'state', 'pop', 'debt'], # assigning non-existent column yields NaNs
                      index=['one', 'two', 'three', 'four',
                             'five', 'six'])
frame2
# type(frame2) # pandas.core.frame.DataFrame

In [ ]:
frame2.columns

In [ ]:
type(frame2['state']) # pandas.core.series.Series
frame2['state'] # dictionary like notation

In [ ]:
frame2.state # attribute notation

In [ ]:
# Retrieve **ROWS**
frame2.loc['three'] # .loc attribute***

In [ ]:
frame2['debt'] = 16.5
frame2

In [ ]:
frame2['debt'] = np.arange(6.)
frame2

In [ ]:
val = pd.Series([-1.2, -1.5, -1.7], index=['two', 'four', 'five'])
frame2['debt'] = val
frame2

In [ ]:
frame2['eastern'] = frame2.state == 'Ohio' # so weird: A = a1 == a2
frame2

In [ ]:
del frame2['eastern']
frame2.columns
frame2

In [ ]:
pop = {'Nevada': {2001: 2.4, 2002: 2.9},
       'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}
# Dictionary, 'Key': labels
pop

In [ ]:
type({2001: 2.4, 2002: 2.9}) # keys can be integers (non-strings)

In [ ]:
# Pandas DataFrame
frame3 = pd.DataFrame(pop)
frame3

In [ ]:
# pd.DataFrame
type(frame3) # pandas.core.frame.DataFrame
frame3.T # transpose class instance method

In [ ]:
pop

In [ ]:
pd.DataFrame(pop) # , index = [2000, 2001, 2002])

In [ ]:
frame3['Nevada'][:2]

In [ ]:
pdata = {'Ohio': frame3['Ohio'][:-1],
         'Nevada': frame3['Nevada'][:2]}
pd.DataFrame(pdata)

In [ ]:
frame3.index.name = 'year'; frame3.columns.name = 'state'
frame3

In [ ]:
frame3.values

In [ ]:
frame2.values

### Index Objects

In [ ]:
obj = pd.Series(range(3), index=['a', 'b', 'c'])
obj

In [ ]:
index = obj.index
index

In [ ]:
index[1:]

In [ ]:
index[1] = 'd'  # TypeError -- index immutable apparently

In [ ]:
labels = pd.Index(np.arange(3))
labels

In [ ]:
obj2 = pd.Series([1.5, -2.5, 0], index=labels)
obj2

In [ ]:
obj2.index is labels

In [ ]:
frame3
frame3.columns
'Ohio' in frame3.columns
2003 in frame3.index

In [ ]:
dup_labels = pd.Index(['foo', 'foo', 'bar', 'bar'])
dup_labels

## Essential Functionality

### Reindexing

In [ ]:
obj = pd.Series([4.5, 7.2, -5.3, 3.6], index=['d', 'b', 'a', 'c'])
obj

In [ ]:
obj2 = obj.reindex(['a', 'b', 'c', 'd', 'e']) # changed order, preserved index-value pairs
obj2

In [ ]:
obj3 = pd.Series(['blue', 'purple', 'yellow'], index=[0, 2, 4])
print(obj3)
obj3.reindex(range(6), method='ffill') # pad / ffill: propagate last valid observation forward to next valid

In [ ]:
frame = pd.DataFrame(np.arange(9).reshape((3, 3)),
                     index=['a', 'c', 'd'],
                     columns=['Ohio', 'Texas', 'California'])
frame

In [ ]:
frame2 = frame.reindex(['a', 'b', 'c', 'd'])
frame2

In [ ]:
states = ['Texas', 'Utah', 'California']
frame.reindex(columns=states)

In [ ]:
frame.loc[['a', 'b', 'c', 'd'], states]

### Dropping Entries from an Axis

In [ ]:
obj = pd.Series(np.arange(5.), index=['a', 'b', 'c', 'd', 'e'])
obj

In [ ]:
new_obj = obj.drop('c')
new_obj

In [ ]:
obj.drop(['d', 'c'])

In [ ]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
                    index=['Ohio', 'Colorado', 'Utah', 'New York'],
                    columns=['one', 'two', 'three', 'four'])
data

In [ ]:
data.drop(['Colorado', 'Ohio'])

In [ ]:
data.drop('two', axis = 1)

In [ ]:
data.drop(['two', 'four'], axis='columns')

In [ ]:
print(obj)
obj.drop('c', inplace=True)
obj

### Indexing, Selection, and Filtering

In [ ]:
obj = pd.Series(np.arange(4.), index=['a', 'b', 'c', 'd'])
obj

In [ ]:
obj['b']

In [ ]:
obj[1]

In [ ]:
obj[2:4]

In [ ]:
obj[['b', 'a', 'd']]

In [ ]:
obj[[1, 3]]

In [ ]:
obj[obj < 2]

In [ ]:
obj['b':'c']

In [ ]:
obj['b':'c'] = 5
obj

In [ ]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
                    index=['Ohio', 'Colorado', 'Utah', 'New York'],
                    columns=['one', 'two', 'three', 'four'])
data

In [ ]:
data['two']

In [ ]:
data[['three', 'one']]

In [ ]:
data[:2]

In [ ]:
data[data['three'] > 5]

In [ ]:
data < 5

In [ ]:
data[data < 5] = 0
data

#### Selection with loc (l = location) and iloc (i = integer)

In [191]:
data

one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [ ]:
data.loc['Colorado', ['two', 'three']]

In [ ]:
data.iloc[2, [3, 0, 1]]

In [ ]:
data.iloc[2]

In [ ]:
data.iloc[[1, 2], [3, 0, 1]]

In [ ]:
data.loc[:'Utah', 'two']

In [192]:
data.iloc[:, :3][data.three > 5]

one  two  three
Colorado    0    5      6
Utah        8    9     10
New York   12   13     14

### Integer Indexes

In [193]:
ser = pd.Series(np.arange(3.))
ser

0    0.0
1    1.0
2    2.0
dtype: float64

In [ ]:
ser[-1]

In [195]:
ser = pd.Series(np.arange(3.))

In [196]:
ser

0    0.0
1    1.0
2    2.0
dtype: float64

In [197]:
ser2 = pd.Series(np.arange(3.), index=['a', 'b', 'c'])
ser2[-1] # b/c string index

2.0

In [201]:
ser

0    0.0
1    1.0
2    2.0
dtype: float64

In [205]:
ser[:1]

0    0.0
dtype: float64

In [207]:
ser.loc[:1]

0    0.0
1    1.0
dtype: float64

In [203]:
ser.iloc[:1]

0    0.0
dtype: float64

### Arithmetic and Data Alignment

In [208]:
s1 = pd.Series([7.3, -2.5, 3.4, 1.5], index=['a', 'c', 'd', 'e'])
s2 = pd.Series([-2.1, 3.6, -1.5, 4, 3.1],
               index=['a', 'c', 'e', 'f', 'g'])
s1

a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64

In [209]:
s2

a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

In [210]:
s1 + s2 # automatic outer join! labels find each other!!

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [211]:
df1 = pd.DataFrame(np.arange(9.).reshape((3, 3)), columns=list('bcd'),
                   index=['Ohio', 'Texas', 'Colorado'])
df2 = pd.DataFrame(np.arange(12.).reshape((4, 3)), columns=list('bde'),
                   index=['Utah', 'Ohio', 'Texas', 'Oregon'])
df1

b    c    d
Ohio      0.0  1.0  2.0
Texas     3.0  4.0  5.0
Colorado  6.0  7.0  8.0

In [212]:
df2

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [213]:
df1 + df2 # need values in both to avoid NaN

b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

In [214]:
df1 = pd.DataFrame({'A': [1, 2]})
df2 = pd.DataFrame({'B': [3, 4]})
df1

A
0  1
1  2

In [215]:
df2

B
0  3
1  4

In [216]:
df1 - df2

A   B
0 NaN NaN
1 NaN NaN

#### Arithmetic methods with fill values

In [217]:
df1 = pd.DataFrame(np.arange(12.).reshape((3, 4)),
                   columns=list('abcd'))
df2 = pd.DataFrame(np.arange(20.).reshape((4, 5)),
                   columns=list('abcde'))
df2.loc[1, 'b'] = np.nan

In [218]:
df1

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [219]:
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   NaN   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [220]:
df1 + df2

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0   NaN  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [221]:
df1.add(df2, fill_value=0) # insert 0 for missings

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0   5.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [222]:
1 / df1

a         b         c         d
0       inf  1.000000  0.500000  0.333333
1  0.250000  0.200000  0.166667  0.142857
2  0.125000  0.111111  0.100000  0.090909

In [223]:
df1.rdiv(1) # r = arguments flipped

a         b         c         d
0       inf  1.000000  0.500000  0.333333
1  0.250000  0.200000  0.166667  0.142857
2  0.125000  0.111111  0.100000  0.090909

In [224]:
df1.reindex(columns=df2.columns, fill_value=0)

a    b     c     d  e
0  0.0  1.0   2.0   3.0  0
1  4.0  5.0   6.0   7.0  0
2  8.0  9.0  10.0  11.0  0

#### Operations between DataFrame and Series

In [225]:
arr = np.arange(12.).reshape((3, 4))
arr

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [226]:
arr[0]

array([0., 1., 2., 3.])

In [227]:
arr - arr[0]

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

In [229]:
frame = pd.DataFrame(np.arange(12.).reshape((4, 3)),
                     columns=list('bde'),
                     index=['Utah', 'Ohio', 'Texas', 'Oregon'])
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [230]:
series = frame.iloc[0]

series

b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

In [231]:
frame - series

b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

In [ ]:
series2 = pd.Series(range(3), index=['b', 'e', 'f'])
frame + series2

In [ ]:
series3 = frame['d']
frame
series3
frame.sub(series3, axis='index')

### Function Application and Mapping

In [ ]:
frame = pd.DataFrame(np.random.randn(4, 3), columns=list('bde'),
                     index=['Utah', 'Ohio', 'Texas', 'Oregon'])
frame
np.abs(frame)

In [ ]:
f = lambda x: x.max() - x.min()
frame.apply(f)

In [ ]:
frame.apply(f, axis='columns')

In [ ]:
def f(x):
    return pd.Series([x.min(), x.max()], index=['min', 'max'])
frame.apply(f)

In [ ]:
format = lambda x: '%.2f' % x
frame.applymap(format)

In [ ]:
frame['e'].map(format)

### Sorting and Ranking

In [ ]:
obj = pd.Series(range(4), index=['d', 'a', 'b', 'c'])
obj.sort_index()

In [ ]:
frame = pd.DataFrame(np.arange(8).reshape((2, 4)),
                     index=['three', 'one'],
                     columns=['d', 'a', 'b', 'c'])
frame.sort_index()
frame.sort_index(axis=1)

In [ ]:
frame.sort_index(axis=1, ascending=False)

In [ ]:
obj = pd.Series([4, 7, -3, 2])
obj.sort_values()

In [ ]:
obj = pd.Series([4, np.nan, 7, np.nan, -3, 2])
obj.sort_values()

In [ ]:
frame = pd.DataFrame({'b': [4, 7, -3, 2], 'a': [0, 1, 0, 1]})
frame
frame.sort_values(by='b')

In [ ]:
frame.sort_values(by=['a', 'b'])

In [ ]:
obj = pd.Series([7, -5, 7, 4, 2, 0, 4])
obj.rank()

In [ ]:
obj.rank(method='first')

In [ ]:
# Assign tie values the maximum rank in the group
obj.rank(ascending=False, method='max')

In [ ]:
frame = pd.DataFrame({'b': [4.3, 7, -3, 2], 'a': [0, 1, 0, 1],
                      'c': [-2, 5, 8, -2.5]})
frame
frame.rank(axis='columns')

### Axis Indexes with Duplicate Labels

In [ ]:
obj = pd.Series(range(5), index=['a', 'a', 'b', 'b', 'c'])
obj

In [ ]:
obj.index.is_unique

In [ ]:
obj['a']
obj['c']

In [ ]:
df = pd.DataFrame(np.random.randn(4, 3), index=['a', 'a', 'b', 'b'])
df
df.loc['b']

## Summarizing and Computing Descriptive Statistics

In [ ]:
df = pd.DataFrame([[1.4, np.nan], [7.1, -4.5],
                   [np.nan, np.nan], [0.75, -1.3]],
                  index=['a', 'b', 'c', 'd'],
                  columns=['one', 'two'])
df

In [ ]:
df.sum()

In [ ]:
df.sum(axis='columns')

In [ ]:
df.mean(axis='columns', skipna=False)

In [ ]:
df.idxmax()

In [ ]:
df.cumsum()

In [ ]:
df.describe()

In [ ]:
obj = pd.Series(['a', 'a', 'b', 'c'] * 4)
obj.describe()

### Correlation and Covariance

conda install pandas-datareader

In [ ]:
price = pd.read_pickle('examples/yahoo_price.pkl')
volume = pd.read_pickle('examples/yahoo_volume.pkl')

import pandas_datareader.data as web
all_data = {ticker: web.get_data_yahoo(ticker)
            for ticker in ['AAPL', 'IBM', 'MSFT', 'GOOG']}

price = pd.DataFrame({ticker: data['Adj Close']
                     for ticker, data in all_data.items()})
volume = pd.DataFrame({ticker: data['Volume']
                      for ticker, data in all_data.items()})

In [ ]:
returns = price.pct_change()
returns.tail()

In [ ]:
returns['MSFT'].corr(returns['IBM'])
returns['MSFT'].cov(returns['IBM'])

In [ ]:
returns.MSFT.corr(returns.IBM)

In [ ]:
returns.corr()
returns.cov()

In [ ]:
returns.corrwith(returns.IBM)

In [ ]:
returns.corrwith(volume)

### Unique Values, Value Counts, and Membership

In [ ]:
obj = pd.Series(['c', 'a', 'd', 'a', 'a', 'b', 'b', 'c', 'c'])

In [ ]:
uniques = obj.unique()
uniques

In [ ]:
obj.value_counts()

In [ ]:
pd.value_counts(obj.values, sort=False)

In [ ]:
obj
mask = obj.isin(['b', 'c'])
mask
obj[mask]

In [ ]:
to_match = pd.Series(['c', 'a', 'b', 'b', 'c', 'a'])
unique_vals = pd.Series(['c', 'b', 'a'])
pd.Index(unique_vals).get_indexer(to_match)

In [ ]:
data = pd.DataFrame({'Qu1': [1, 3, 4, 3, 4],
                     'Qu2': [2, 3, 1, 2, 3],
                     'Qu3': [1, 5, 2, 4, 4]})
data

In [ ]:
result = data.apply(pd.value_counts).fillna(0)
result

## Conclusion

In [ ]:
pd.options.display.max_rows = PREVIOUS_MAX_ROWS